services:
  backend:
    build: ../exercise4
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - db_data:/app/data

  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8080

volumes:
  db_data:
