version: "2"
run:
  go: "1.24"
  modules-download-mode: readonly
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/mikolajskalka/ebiznes/exercise4
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
