name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  golangci-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exercise4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          working-directory: ./exercise4
          args: --timeout=5m
